force-app/main/default/objects/OpenAIAPISetting__mdt/OpenAIAPISetting__mdt.object-meta.xml
<CustomObject>
    <label>OpenAI API Setting</label>
    <pluralLabel>OpenAI API Settings</pluralLabel>
</CustomObject>

force-app/main/default/objects/OpenAIAPISetting__mdt/fields/API_Key__c.field-meta.xml
<CustomField>
    <fullName>API_Key__c</fullName>
    <label>API Key</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/OpenAIAPISetting__mdt/fields/Model__c.field-meta.xml
<CustomField>
    <fullName>Model__c</fullName>
    <label>Model</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>gpt-3.5-turbo</fullName>
                <default>true</default>
                <label>gpt-3.5-turbo</label>
            </value>
            <value>
                <fullName>gpt-3.5-turbo-16k</fullName>
            </value>
            <value>
                <fullName>gpt-4</fullName>
            </value>
            <value>
                <fullName>gpt-4-32k</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/AI_OpenAIFlowUtility.cls
public with sharing class AI_OpenAIFlowUtility {

    public class InputVariable {
        @InvocableVariable
        public String systemRole;

        @InvocableVariable
        public String userContent;
    }

    public class ReturnVariable {
        @InvocableVariable
        public String gptResponse;
    }
    
    @InvocableMethod(label='Call OpenAI Chat API' description='Return responses from the OpenAI Chat API based on user input')
    public static List<ReturnVariable> processGPTChatFromFlow(List<InputVariable> inputVariables) {
        
        OpenAIAPISetting__mdt settings = OpenAIAPISetting__mdt.getInstance('GPT_From_Flow');

        //Parse the inputs
        String systemRole = inputVariables.get(0).systemRole;
        String userContent = inputVariables.get(0).userContent;

        AI_GPTResponseWrapper gptResponse = AI_OpenAIAPIUtility.processGPTChat(systemRole, userContent, settings.Endpoint__c, settings.API_Key__c, settings.Model__c);

        List<ReturnVariable> returnVariableList = new List<ReturnVariable>();
        ReturnVariable returnVar = new ReturnVariable();
        if(gptResponse.isSuccess) {
            returnVar.gptResponse = gptResponse.choices[0].message.content;
        }
        else {
            returnVar.gptResponse = System.Label.AI_General_API_Error + ' ' + gptResponse.error.message;
        }
        
        returnVariableList.add(returnVar);

        return returnVariableList;
    }
}