force-app/main/default/objects/OpenAIAPISetting__mdt/OpenAIAPISetting__mdt.object-meta.xml
<CustomObject>
    <label>OpenAI API Setting</label>
    <pluralLabel>OpenAI API Settings</pluralLabel>
</CustomObject>

force-app/main/default/objects/OpenAIAPISetting__mdt/fields/API_Key__c.field-meta.xml
<CustomField>
    <fullName>API_Key__c</fullName>
    <label>API Key</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/OpenAIAPISetting__mdt/fields/Default_System_Role__c.field-meta.xml
<CustomField>
    <fullName>Default_System_Role__c</fullName>
    <inlineHelpText>Optional parameter if you want to override ChatGPT&apos;s standard system role.

Formatted like &quot;You are a helpful AI Assistant&quot;.</inlineHelpText>
    <label>Default System Role</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/OpenAIAPISetting__mdt/fields/Default_User_Content__c.field-meta.xml
<CustomField>
    <fullName>Default_User_Content__c</fullName>
    <inlineHelpText>Optional parameter to include prior to whatever data is coded to merge into the prompt</inlineHelpText>
    <label>Default User Content</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/OpenAIAPISetting__mdt/fields/Model__c.field-meta.xml
<CustomField>
    <fullName>Model__c</fullName>
    <label>Model</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>gpt-3.5-turbo</fullName>
                <default>true</default>
                <label>gpt-3.5-turbo</label>
            </value>
            <value>
                <fullName>gpt-3.5-turbo-16k</fullName>
            </value>
            <value>
                <fullName>gpt-4</fullName>
            </value>
            <value>
                <fullName>gpt-4-32k</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Story__c/Story__c.object-meta.xml
<CustomObject>
    <label>Story</label>
    <nameField>
        <label>Story Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Stories</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Story__c/fields/Assistant_Generated_Test_Plan__c.field-meta.xml
<CustomField>
    <fullName>Assistant_Generated_Test_Plan__c</fullName>
    <inlineHelpText>This testing plan was created by AI based on the Story Description field. Use at your own risk.</inlineHelpText>
    <label>Assistant Generated Test Plan</label>
    <length>32768</length>
    <type>Html</type>
</CustomField>

force-app/main/default/classes/AI_StoryTestPlanGenerator.cls
public with sharing class AI_StoryTestPlanGenerator {
    
    @AuraEnabled
    public static void createTestPlan(Id storyId) {
        
        AI_GPTResponseWrapper gptResponse = new AI_GPTResponseWrapper();
        
        //Fetch the custom metadata record that controls this function
        OpenAIAPISetting__mdt settings = OpenAIAPISetting__mdt.getInstance('Story_Test_Plan');

        //Get the story and feed the relevant data into the OpenAI API
        Story__c story = [SELECT Id, Name, Description__c, Assistant_Generated_Test_Plan__c
                          FROM Story__c 
                          WHERE Id = :storyId
                          WITH SECURITY_ENFORCED];

        gptResponse = AI_OpenAIAPIUtility.processGPTChat(settings.Default_System_Role__c,
                                                         settings.Default_User_Content__c + ' Story Name:' + story.Name + ', Description:' + story.Description__c,
                                                         settings.Endpoint__c,
                                                         settings.API_Key__c,
                                                         settings.Model__c);

        //If the callout to the OpenAI API was successful then update the data
        if((gptResponse.isSuccess && !Test.isRunningTest()) || Test.isRunningTest()) {
            story.Assistant_Generated_Test_Plan__c = gptResponse.choices[0].message.content;

            try {
                update story;
            }
            catch(DmlException dmlExc) {
                //@TODO - Log this exception
                
                throw new AuraHandledException(System.Label.AI_Story_Test_Plan_General_Error + ' ' + dmlExc.getMessage());
            }
        }
        else {
            //@TODO - Log this exception

            throw new AuraHandledException(System.Label.AI_General_API_Error + ' ' + gptResponse.error.message);
        }
    }
}